services:
  api:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - ./Master:/app/Master
      - ./CyPhy:/app/CyPhy
    env_file:
      - .env
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: 